set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set number
set relativenumber
set mouse=a
set exrc
set guicursor=
set nohlsearch
set hidden
set ignorecase
set smartcase
set noerrorbells
set nowrap
set expandtab
set noswapfile
set nobackup
set undodir
set incsearch
set scrolloff=8
set signcolumn=yes
set colorcolumn=80
set path+=**
set wildmenu
set wildignore+=**/node_modules/**
